default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: demo_app_development

test:
  <<: *default
  database: demo_app_test
production:
  primary: &primary_production
    <<: *default
    database: demo_app_production
    username: root
    password: password
  cache:
    <<: *primary_production
    database: demo_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: demo_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: demo_app_production_cable
    migrations_paths: db/cable_migrate
